WITH
    ethereum_users AS (
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_ethereum.RangeProtocolVault_evt_Minted
        UNION
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_ethereum.RangeProtocolVault_evt_Burned
    ),
    arbitrum_users AS (
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_arbitrum.RangeProtocolVault_evt_Minted
        UNION
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_arbitrum.RangeProtocolVault_evt_Burned
    ),
    base_users AS (
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_base.RangeProtocolVault_evt_Minted
        UNION
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_base.RangeProtocolVault_evt_Burned
    ),
    bnb_users AS (
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_bnb.RangeProtocolVault_evt_Minted
        UNION
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_bnb.RangeProtocolVault_evt_Burned
    ),
    polygon_users AS (
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_polygon.RangeProtocolVault_evt_Minted
        UNION
        SELECT
            receiver,
            contract_address
        FROM
            range_protocol_polygon.RangeProtocolVault_evt_Burned
    ),
    all_users AS (
        SELECT
            receiver
        FROM
            ethereum_users
        UNION
        SELECT
            receiver
        FROM
            arbitrum_users
        UNION
        SELECT
            receiver
        FROM
            base_users
        UNION
        SELECT
            receiver
        FROM
            bnb_users
        UNION
        SELECT
            receiver
        FROM
            polygon_users
    )
SELECT
    'Total Unique Users' AS chain,
    COUNT(DISTINCT receiver) AS user_count
FROM
    all_users;
